[workspace]
resolver = "2"
members = [
  "crates/*",
]

[workspace.dependencies]
log = "0.4"
logos = "0.12"
anyhow = { version = "1", features = ["backtrace"] }
thiserror = "1.0"
regex = "1"
lalrpop-util = "0.19.8"
lalrpop = "0.19.8"
